### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by AlgusDark** [AlgusDark/expressful-pot#1]
- [ ] Mongoose Model Validations for usage in controllers errors outputs
- [ ] **limit**/**page** parameter for **GET** `api/v1/users`.
- [ ] Use JSDoc
- [ ] Proper Testing with [TAPE](https://github.com/substack/tape) and [Supertest](https://github.com/visionmedia/supertest).
- [] Find better way to implement seeds
